### ISSUE TITLE
Staging: Password reset form gives error

### ISSUE THREAD

**Issue by jetlej** [jetlej/HE-6.0-Bugs#204] opened 2016-01-02 00:10 UTC
When resetting your password on hiexistence.com, the console shows this error when typing in the second box:

user-profile.min.js?ver=4.3.1:1 Uncaught TypeError: Cannot read property 'className' of undefined

**Comment by dpatil-gmcs** [comment] 2016-01-04 07:35
@jetlej : We would need SSH / RDP access to figure out the cause for this issue as we have to LOOK at the Nginx / PHP Logs to check what is going wrong in the background at the server level. As we cannot predict the root cause with a read only view of the Staging site.

Awaiting your response. Thanks !

**Comment by jetlej** [comment] 2016-01-04 16:19
@dpatil-gmcs - I'm messaging you in Slack with SSH credentials

**Comment by dpatil-gmcs** [comment] 2016-01-06 06:19
@jetlej : Awaiting for the SSH Credentials from your side.

**Comment by dpatil-gmcs** [comment] 2016-01-08 10:28
@jetlej : 
We have connected to host using FTP credentials but it is empty. Please refer following screengrab
![selection_085](https://cloud.githubusercontent.com/assets/5171153/12195862/8a464ea0-b620-11e5-9a13-048ca2c68be2.png)

**Comment by jetlej** [comment] 2016-01-08 16:12
@dpatil-gmcs - staging is hosted in the dev.highexistence.com folder

**Comment by dpatil-gmcs** [comment] 2016-01-11 05:20
@jetlej : I understand, but with the credentials you have provided us for FTP, we do NOT see any folder structure under ROOT..Looks empty as in the above screenshot..Can you please confirm ? Thanks !

**Comment by jetlej** [comment] 2016-01-12 14:31
Oh sorry about that. It's fixed now!

**Comment by jetlej** [comment] 2016-01-14 15:28
@dpatil-gmcs - This is not fixed for me on hiexistence.com. 

<img width="394" alt="screen shot 2016-01-14 at 10 27 56 am" src="https://cloud.githubusercontent.com/assets/1179057/12328470/80ad6be8-baa9-11e5-90a5-a22730aacbd4.png">

**Comment by dpatil-gmcs** [comment] 2016-01-15 05:50
@jetlej : From our comments above, it is obvious that we have NOT started work on this task. We are still waiting on you for the FTP Credentials... Your comment above "Oh sorry about that. It's fixed now! - @dpatil-gmcs" made us feel that you have resolved this issue.

**Comment by dpatil-gmcs** [comment] 2016-01-18 14:08
@jetlej : Could you SLACK Message me the phpmyadmin URL ?

**Comment by jetlej** [comment] 2016-01-18 17:31
@dpatil-gmcs - I did fix the issue. Your same FTP credentials will now work to access the correct folder in FTP. I used them to login and it worked.

**Comment by dpatil-gmcs** [comment] 2016-01-21 06:39
@jetlej : If the issue is fixed, how do we test it. I think SMTP is not configured on the test site.

**Comment by jetlej** [comment] 2016-01-27 18:40
@dpatil-gmcs - I was saying that I fixed the FTP problem. I did not fix this particular Github issue

**Comment by jetlej** [comment] 2016-01-27 18:42
@dpatil-gmcs - I just tested this again. The email is going out, so SMPT is working fine.

Try this password reset link to see the issue: http://hiexistence.com/resetpass/?key=IJKacGJ1XJge8y4VSmKu&login=jordan

**Comment by dpatil-gmcs** [comment] 2016-02-02 11:05
@jetlej  There is a problem in the wordpress core file. I think upgrading wordpress to latest version(4.4.1) will fix the problem. The issue seems to be related to #220, solving this issue must fix the problem.

**Comment by MSchirp** [comment] 2016-02-03 17:21
Go ahead with #220!

**Comment by dpatil-gmcs** [comment] 2016-02-10 14:12
@MSchirp #220 is closed, Yet this issue persists, Seems like it is a plugin related issue. I found the similar kind of issue on the following url: https://wordpress.org/support/topic/tml-reset-password-is-not-working-properly awaiting their response.

**Comment by dpatil-gmcs** [comment] 2016-04-07 09:02
@MSchirp @jetlej   The problem is solved now, somebody had changed the Reset Password page template to 'Default Template', which caused the problem.

**Closed by dpatil-gmcs** 2016-04-07 09:02 UTC
Labels: bug, discussing
