### ISSUE TITLE
Shortcodes request

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#286] opened 2016-04-18 10:18 UTC
Would it be possible for you to code up buttons like these which we could use as short codes in articles? 

This would be very handy for promoting amazon and blinkist products:

![screenshot 2016-04-18 17 16 24](https://cloud.githubusercontent.com/assets/13107838/14600942/73357b1a-0589-11e6-8663-860b2a992461.png)

@dpatil-gmcs

**Comment by MSchirp** [comment] 2016-04-20 15:48
Can you be a bit more specific? This is definitely doable.

**Comment by JonBrooksX** [comment] 2016-04-21 06:07
Sure. 

I think we should be basically copy these buttons exactly as they are, except change the green color to a purple on the "read in 15 minutes" button. 

![screenshot 2016-04-21 12 46 32](https://cloud.githubusercontent.com/assets/13107838/14699410/bc83aa32-07c1-11e6-88af-768993b6716e.png)

I'd like to have three shortcodes. 

1) a single button in the style of "buy this book" button
2) a single button in the style of "read in 15 minutes" button
3) two buttons side by side, one in each style

Let me know if this is unclear.

**Comment by dpatil-gmcs** [comment] 2016-04-27 13:44
@JonBrooksX  @MSchirp 
We have implemented the shortcodes for both the buttons and committed the code to the TEST site.
The Shortcode to use Buy Button is:
[buyButton url=""]
Shortcode for Read Button
[readButton url=""]
and the Shortcode to use both the buttons:
[buyRead buyurl="" readurl=""]

The URLs to the buy and read link must be given in the shortcode, so that the button redirects to the specified URL.

I have attached the screenshots of all  the three buttons below, Please have a look and let us know  your views on it.
![buybutton](https://cloud.githubusercontent.com/assets/5171153/14854145/26a67c16-0cac-11e6-8ee4-3a8467d875cd.png)

![readbutton](https://cloud.githubusercontent.com/assets/5171153/14854161/33a779d8-0cac-11e6-81a7-58e4326e44fd.png)

![bothbuttons](https://cloud.githubusercontent.com/assets/5171153/14854170/3a19d3ec-0cac-11e6-9b71-e867b8b3c80e.png)

**Comment by JonBrooksX** [comment] 2016-04-29 15:38
Hey @dpatil-gmcs, great job on the buttons. 

Two small points: 

1) Can you make the edges rounder? I want them to be rounded rectangles. Not TOO MUCH, but more than it is now. 

2) Can you make the grey border on the "but the book" button darker so it matches the same color as the text inside?

**Comment by dpatil-gmcs** [comment] 2016-05-04 13:34
@MSchirp @JonBrooksX  We have made the recommended changes and committed the code to the TEST site.
The shortcodes are implemented on the Test Post created by us on TEST site.    http://hiexistence.com/test-post/

Following is the screenshot of the test post:
![modifiedbuttons](https://cloud.githubusercontent.com/assets/5171153/15015695/fedb1456-122a-11e6-8b25-8ab9118da6a6.png)

Please have a look and let us know your views on it!

**Comment by JonBrooksX** [comment] 2016-05-04 17:24
Hey, that looks great @dpatil-gmcs 

One final thing. Make the space between the two side-by-side buttons three times larger.

**Comment by dpatil-gmcs** [comment] 2016-05-05 13:49
@JonBrooksX  @MSchirp  This task is implemented, We have increased the space between two buttons, Please have a look and let us know your views on it.

Screenshot:
![buttons](https://cloud.githubusercontent.com/assets/5171153/15045069/37cade92-12f6-11e6-9cae-6b43db458926.png)

**Comment by dpatil-gmcs** [comment] 2016-05-09 11:08
@JonBrooksX  @MSchirp  Any Updates for us?

**Comment by JonBrooksX** [comment] 2016-05-10 19:17
Yeah, this looks great to me @dpatil-gmcs. I'm happy for you to push it to the live site.

**Comment by dpatil-gmcs** [comment] 2016-05-12 13:04
@JonBrooksX  @MSchirp  We have deployed the code to the LIVE site. Now you will be able to use the shortcodes to display the buttons.

Please have a look and give us a sign-off so that we can close the issue.

**Comment by JonBrooksX** [comment] 2016-05-13 08:02
I just tested it. Looks great, and works perfectly. Awesome work @dpatil-gmcs. You can close this issue now.

**Comment by dpatil-gmcs** [comment] 2016-05-13 10:57
@JonBrooksX  Thanks. Closing the issue!

**Comment by JonBrooksX** [comment] 2016-05-20 12:52
Hey @dpatil-gmcs 

There's a little bug with the short codes button:

When you click the button it redirects you to a new page, but when you return to the blog article with the button in, the button text disappears. See screenshot: 

![screenshot 2016-05-20 19 43 04](https://cloud.githubusercontent.com/assets/13107838/15428225/448f142a-1ec4-11e6-8b2b-f221cafe98d5.png)

Would you be able to fix this?

**Comment by MSchirp** [comment] 2016-05-26 12:42
Also, the Shortcode to use both the buttons does not work:
[buyRead buyurl="" readurl=""]

When using it the buttons do show up, but clicking them doesn't lead to the specified links, it just refreshes the page.

**Comment by dpatil-gmcs** [comment] 2016-05-27 13:10
@MSchirp @JonBrooksX  We have fixed the problem reported by the @JonBrooksX. Tested it and now we have deployed the code to the TEST site, Please have a look and let us know your views on it.
@MSchirp  the problem that you are facing is not reproducible at my side can you please provide the url so that I can crosscheck and solve the problem.

**Comment by JonBrooksX** [comment] 2016-05-29 09:09
@dpatil-gmcs The buttons don't disappear anymore. That problem is solved. 

However, the two buttons side-by-side are not working for me.

**Comment by dpatil-gmcs** [comment] 2016-05-30 13:47
@JonBrooksX  @MSchirp  We have implemented the fix for two buttons, We have tsted it on TEST site and our local site, it seems to be working fine.
The code is committed to the LIVE site, Please have a look and give us a sign-off so that we can close the issue. 

Thanks :)

**Comment by JonBrooksX** [comment] 2016-05-30 16:43
Just checked on the LIVE site and the shortcodes are working perfectly. :)

Thanks! You can close now.

**Closed** 2016-05-31 09:28 UTC
Labels: discussing, ready for review
