### ISSUE TITLE
Still having issues with the 'Sign In' function on HE

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#284] opened 2016-04-16 21:37 UTC
I just tried to use the FB 'Sign In' function. First, it took me back to the homepage, where it was still displaying the 'Join' and 'Sign In' buttons, which should disappear when a user is signed in. There was no sign of my notification and profile icons. Then, I clicked on another page and the top left spot on the navbar looked like this:

![screen shot 2016-04-16 at 3 32 37 pm](https://cloud.githubusercontent.com/assets/9164601/14583750/c5fb6dd4-03e8-11e6-8be9-f66832ae01d6.png)

I clicked 'Sign In' yet again, clicked the FB 'Sign In' button, and the loading icon appeared. It kept loading and loading for about two minutes, never signing me in. I went back to the homepage and started clicking 'Sign In.' Each time I clicked it, it would just reload the homepage without signing me in. Finally, I clicked 'Sign In' on a non-homepage and manually entered my username and password. Finally, this worked, and I was signed in. 

We really need to get these issues resolved ASAP, as they ruin the UX and make the site seem very broken/buggy.

**Comment by lostboyevsky** [comment] 2016-04-16 21:37
Are you guys having these issues, @MSchirp and @JonBrooksX?

**Comment by dpatil-gmcs** [comment] 2016-04-19 14:00
@MSchirp  @lostboyevsky   I tried to reproduce the issue, and I was able to reproduce it sometimes, I think there is some problem with the Super Socializer plugin.
I will need to investigate the plugin code to find why this is happening.

**Comment by dpatil-gmcs** [comment] 2016-04-21 13:45
@lostboyevsky @MSchirp  We have investigated a bit, and we observed that the Super Socializer plugin,  is malfunctioning, There can be many reasons behind it, the major reason is installation of any conflicting plugin or settings.

We will need some more time to investigate the cause for such behaviour.

**Comment by dpatil-gmcs** [comment] 2016-04-22 13:35
@lostboyevsky  @MSchirp  Made the necessary changes, and Now the issue seems to be fixed for us,
We have tested on multiple browsers and sandboxes. Please have a look at it, and give us a sign-off so that we can close the issue.

**Closed** 2016-04-23 15:57 UTC
Labels: bug, discussing, urgent
