### ISSUE TITLE
'Recommended posts' sidebar widget is malfunctioning

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#281] opened 2016-04-05 02:41 UTC
I just mentioned this in issue #280, but I just realized that it isn't only happening on posts below a single post on the infinite scroll. It's happening on any blog post. First of all, the 'recommended posts' widget takes about *30 seconds* to load for me. Second, once it does load, it's being all buggy and showing duplicate posts. Look: 

![screen shot 2016-04-04 at 10 34 36 pm](https://cloud.githubusercontent.com/assets/9164601/14269816/4037da9c-fab6-11e5-9cc8-e62a922f9223.png)

I'm in Chrome on my Mac.

**Comment by lostboyevsky** [comment] 2016-04-05 03:18
Upon further testing, I've noticed that the problem is *definitely worse* on longer posts --- posts in which there are in-post ads. So in order to take a look at this problem, @dpatil-gmcs, check out some longer posts like this one: http://highexistence.com/12-psychological-tactics-donald-trump-uses-to-manipulate-the-masses/

**Comment by dpatil-gmcs** [comment] 2016-04-12 13:55
@MSchirp  @lostboyevsky  I can see that the issue occurs only if page is scrolled up and down before the Sajari recommendations are loaded.
If the page is not scrolled till it is completely loaded the sidebar looks good.
I will have investigate the code and find the reason behind it.
Will Update you once I have a clue.

**Comment by MSchirp** [comment] 2016-04-13 15:56
@dpatil-gmcs Why are they loading so slowly in the first place?

@mish15

**Comment by mish15** [comment] 2016-04-13 22:21
@MSchirp looking at that page, they aren't being requested for about 20 seconds because there's so much other stuff loading (325 assets). They're put in the window load event, which is delayed quite a bit. @dpatil-gmcs might be better in the document.ready event? 4 sec vs 20 sec. 

![screen shot 2016-04-14 at 8 16 59 am](https://cloud.githubusercontent.com/assets/869412/14511249/7b46a50e-0219-11e6-8792-15cb3afa6561.png)

@lostboyevsky not sure about the duplicates. We aren't controlling the numbering, etc. Looking at the code, seems there might be a fall back to replace recommendations with a different type? I can't replicate this though.

**Comment by mish15** [comment] 2016-04-14 00:47
@dpatil-gmcs might be easier to just use the HTML integration. Sample below, CSS is pretty close to your existing, but easy to change as needed. The HTML has the advantage that it loads optimistically, handles click tracking, rendering, etc for you.

```html
</style>
  <div data-sj-related data-sj-thumbnail data-sj-maxresults="4" data-sj-filters="post-type,post|!=series-id,0" data-sj-meta-category="Random + Awesome"></div>
  <div data-sj-recent data-sj-thumbnail data-sj-maxresults="3" data-sj-scales="post-id,1000000,1000000,5,0" filters="post-type,post" data-sj-meta-category="Random + Awesome"></div>
  <div data-sj-popular data-sj-thumbnail data-sj-maxresults="3" filters="post-type,post"></div>
</div>
```

```css
.sj-result-item {
  display: block;
  border-bottom: 1px solid #F3F5F6;
  padding: 0 0 20px;
  margin-bottom: 20px;
}
.sj-result-thumb {
  height: 100px;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
  background-color: #283235;
  background-position: center center;
  background-repeat: none;
  position: relative;  
}
.sj-result-title {
  padding: 10px 0 0;
}
.sj-result-link {
  font-size: 14px;
  line-height: 140%;
  font-weight: bold;
  color: #283235;
  text-transform: uppercase;
}
.sj-result-meta-desc {
  display:none;
}
```

**Comment by dpatil-gmcs** [comment] 2016-04-14 14:05
@MSchirp @mish15 
@mish15  Do you want me to change the window load event to document ready?
And Can you please explain us the HTML integration point. It is bit unclear to us.

**Comment by mish15** [comment] 2016-04-14 21:45
@dpatil-gmcs 1. doc ready, yes, this will dramatically improve the load issue. 2. We offer JavaScript or HTML integration, you are currently using JavaScript, which you have written some code for. The HTML integration is an alternative "cut and paste" option that handles loading, requests, rendering, click tracking, etc automatically. I mentioned this as it's just much simpler to integrate, but also much easier for us to debug with queries like this (it's been heavily optimised in terms of loading, tracking, etc).

If you wanted to change to this, you just keep the install tag and put in the above code, you don't need to write the custom JavaScript loading and event handling, so it should make things easier at your end.

**Comment by dpatil-gmcs** [comment] 2016-04-19 13:57
@MSchirp @lostboyevsky We have made the changes to the code, there was some logical mistake in the previously written code. The code is fixed now and the problem seems to be solved at our end.

Please have a look and let us know your views on it, also give us a signoff so that we can close the issue.

**Comment by MSchirp** [comment] 2016-04-19 14:03
Can you confirm its not happening anymore @lostboyevsky ?

**Comment by dpatil-gmcs** [comment] 2016-04-21 13:41
@lostboyevsky  @MSchirp  Any updates for us?

**Comment by lostboyevsky** [comment] 2016-04-22 09:40
@dpatil-gmcs, can confirm that it's not happening anymore.

**Comment by dpatil-gmcs** [comment] 2016-04-22 11:44
@MSchirp @lostboyevsky  Seems like the issue is fixed now, so closing the issue.

**Comment by MSchirp** [comment] 2016-05-04 17:10
It still takes around ±30 seconds for this widget to load. This is a problem, because a lot of our visitors don't stay longer on the page than 30 seconds, and when they want to go to a different page, they don't see our own in house alternatives. Please make sure this one is loaded immediately after the advertising, which loads in a few seconds.

@mish15 Any suggestions? thanks! :-)

**Comment by mish15** [comment] 2016-05-05 01:45
@MSchirp looks like it's just too much JavaScript (~3MB). Our requests are triggered on the load event, they respond quickly but don't render for a while (nothing much we can do), seems it's just queued while other stuff processes. The site is pretty well optimised for speed except for the JavaScript, so you might need some work done there.

![screen shot 2016-05-05 at 10 45 07 am](https://cloud.githubusercontent.com/assets/869412/15034168/2affec4c-12b6-11e6-86de-c042266dee26.png)

There are some tools to look at this stuff, synchronous JavaScript is a problem, see https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fhighexistence.com%2F12-psychological-tactics-donald-trump-uses-to-manipulate-the-masses%2F: 

```
http://highexistence.com/…hethen/js/jquery-1.11.2.min.js?ver=4.4.2
http://highexistence.com/…dal-login/assets/js/scripts.js?ver=4.4.2
http://highexistence.com/…ns-voting/js/hethens-voting.js?ver=5.4.3
http://highexistence.com/…nts/js/jquery.countdown.min.js?ver=4.4.2
http://highexistence.com/…/js/jquery/jquery.color.min.js?ver=2.1.1
http://highexistence.com/…ns/ajaxed-comments/js/front.js?ver=4.4.2
http://highexistence.com/…ress/bp-core/js/confirm.min.js?ver=2.5.1
http://highexistence.com/…/js/wp-ajaxify-comments.min.js?ver=1.4.0
http://highexistence.com/…bp-core/js/jquery-query.min.js?ver=2.5.1
http://highexistence.com/…p-core/js/jquery-cookie.min.js?ver=2.5.1
http://highexistence.com/…t/themes/hethen/_inc/global.js?ver=2.5.1
```

Also see https://gtmetrix.com/reports/highexistence.com/MPymyjYL: 

```
2.7MiB of JavaScript is parsed during initial page load. Defer parsing JavaScript to reduce blocking of page rendering.

https://s.ytimg.com/yts/jsbin/player-en_US-vflL5aRF-/base.js (948.7KiB)
https://s.ytimg.com/yts/jsbin/player-en_US-vflL5aRF-/base.js (948.7KiB)
http://highexistence.com/wp-content/themes/hethen/js/minified/scripts.min.js?rel=1456485162849 (205.4KiB)
https://s.ytimg.com/yts/jsbin/www-embed-player-vfluJ0hSy/www-embed-player.js (166.8KiB)
https://s.ytimg.com/yts/jsbin/www-embed-player-vfluJ0hSy/www-embed-player.js (166.8KiB)
http://highexistence.com/wp-content/themes/hethen/js/jquery-1.11.2.min.js?ver=4.4.2 (85.8KiB)
http://a.optnmnstr.com/app/js/api.min.js?ver=1.1.4.5 (53.5KiB)
http://highexistence.com/wp-content/plugins/wp-ajaxify-comments/js/wp-ajaxify-comments.min.js?ver=1.4.0 (30.8KiB)
http://staticxx.facebook.com/connect/xd_arbiter.php?version=42 (29.1KiB of inline JavaScript)
https://staticxx.facebook.com/connect/xd_arbiter.php?version=42 (29.1KiB of inline JavaScript)
http://highexistence.com/wp-content/themes/hethen/_inc/global.js?ver=2.5.1 (23.3KiB)
http://highexistence.com/wp-content/plugins/ajaxed-comments/js/front.js?ver=4.4.2 (15.6KiB)
http://highexistence.com/wp-content/plugins/ajaxed-comments/js/jquery.countdown.min.js?ver=4.4.2 (12.9KiB)
http://highexistence.com/12-psychological-tactics-donald-trump-uses-to-manipulate-the-masses/ (11.7KiB of inline JavaScript)
https://cdn3.doubleverify.com/t2tv7.html (11.1KiB of inline JavaScript)
http://highexistence.com/wp-includes/js/jquery/jquery.color.min.js?ver=2.1.1 (7.5KiB)
https://www.facebook.com/v2.0/plugins/like.php?action=like&app_id=157883130910345&channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D42%23cb%3Df468b83a9bbc7c%26domain%3Dhighexistence.com%26origin%3Dhttp%253A%252F%252Fhighexistence.com%252Ff332139db42a78%26relation%3Dparent.parent&container_width=0&href=https%3A%2F%2Ffacebook.com%2Fhighexistence&layout=button_count&locale=en_US&sdk=joey&share=false&show_faces=false (5.0KiB of inline JavaScript)
https://www.facebook.com/plugins/subscribe.php?href=https%3A%2F%2Fwww.facebook.com%2Fjordanbates4&layout=standard&show_faces=false&colorscheme=light&font=lucida+grande&width=500&appId=135192646575285 (4.1KiB of inline JavaScript)
http://highexistence.com/wp-content/plugins/super-socializer/js/front/social_login/common.js?ver=7.6 (3.4KiB)
http://highexistence.com/wp-content/plugins/hethens-voting/js/hethens-voting.js?ver=5.4.3 (1.9KiB)
https://www.youtube.com/embed/9LR6EA91zLo?feature=oembed (1.8KiB of inline JavaScript)
https://www.youtube.com/embed/MvVfj0ov8k8?feature=oembed (1.8KiB of inline JavaScript)
http://highexistence.com/wp-content/plugins/cd-bp-avatar-bubble/_inc/hover.js?ver=4.4.2 (1.8KiB)
http://highexistence.com/wp-content/plugins/ajax-bootmodal-login/assets/js/scripts.js?ver=4.4.2 (1.7KiB)
http://highexistence.com/wp-content/plugins/buddypress/bp-core/js/jquery-cookie.min.js?ver=2.5.1 (1.2KiB)
http://highexistence.com/wp-content/plugins/super-socializer/js/front/facebook/sdk.js?ver=7.6 (1.1KiB)
http://highexistence.com/wp-content/plugins/super-socializer/js/front/social_login/general.js?ver=7.6 (975B)
http://highexistence.com/wp-content/plugins/super-socializer/js/front/social_login/facebook.js?ver=7.6 (416B)
http://highexistence.com/wp-content/plugins/buddypress/bp-core/js/jquery-query.min.js?ver=2.5.1 (117B)
http://highexistence.com/wp-content/plugins/buddypress/bp-core/js/confirm.min.js?ver=2.5.1 (112B)
```

**Comment by MSchirp** [comment] 2016-05-09 09:40
@dpatil-gmcs Please have a look

**Comment by dpatil-gmcs** [comment] 2016-05-10 11:46
@MSchirp  As the javascript files, are the plugin files, eliminating scripts won't be a good Idea.
I am trying to make the scripts asynchronous so that the problem should be solved.
this issue is related to #193

**Comment by MSchirp** [comment] 2016-05-10 15:08
Asynchronous sounds like a good idea, thanks!

**Comment by dpatil-gmcs** [comment] 2016-05-17 13:45
@MSchirp  Just an FYI, We had tried a plugin to make scripts async, the plugin works when we test for the google insights score, but the plugin affects site's infinite scroll functionality and some other functionalities like sajari loading etc.
So I think the use of this plugin is not a good Idea.
The plugin url is:
https://wordpress.org/plugins/async-js-and-css/

I will still continue my research on this to find a better solution.

**Comment by MSchirp** [comment] 2016-05-17 13:55
Yeah, that's not good. Would there be a way to load the scripts in a different order? 

First: content of the website
Then: ads + and then + sajari
Last: infinite scroll etc.

?

**Comment by mish15** [comment] 2016-05-17 20:22
Our script is already async.

**Comment by dpatil-gmcs** [comment] 2016-05-23 13:22
@MSchirp  As per @mish15  the Sajari scripts are in sync, 
I think the sajari suggestions loads slow because of the plugin scripts, that might be loading slow, we are now researching on the way we can load all the scripts in Async.

**Comment by dpatil-gmcs** [comment] 2016-05-24 13:53
@MSchirp  Today I have researched a bit more about faster loading of the scripts and found a couple of plugins,
I have tried some of the plugins on the TEST site, but it seems that to minify/async the blocking scripts breat some of the functionalites of the site.

After some more research, I found another plugin 'Better WordPress Minify' which does the work and make sajari loading faster than before. 
I have installed the plugin to the TEST site, Please have a look and let me know your views on it.

**Comment by MSchirp** [comment] 2016-05-27 13:33
Please push to live, ill check it there.

**Comment by dpatil-gmcs** [comment] 2016-05-27 13:50
@MSchirp  Pushed it to LIVE please have a look.

**Comment by lostboyevsky** [comment] 2016-05-27 18:55
recommendation sidebar still seems to be taking an exceptionally long time to load for me. however, my internet is rather slow in my current location so it's hard for me to judge too objectively here.

**Comment by JonBrooksX** [comment] 2016-05-28 17:56
I just did some testing.

 The sidebar in Chrome loads in 3-5 seconds, which is pretty good. 

In Safari, it loads in roughly 12-15 seconds. 

I can't explain this. any ideas @dpatil-gmcs ?

**Comment by dpatil-gmcs** [comment] 2016-05-30 13:49
@JonBrooksX  Seems strange, I think there must be script loading time difference on both the browsers. Not sure but we will need to research on it.

**Comment by dpatil-gmcs** [comment] 2016-06-10 14:03
@JonBrooksX  @MSchirp   I have researched and tried to load the scripts faster for safari too,
I have made the changes on the TEST site and tested on safari, The sajari seems to be loaded as soon as the page is loaded,

Please have a look and let us know your views on it.

**Comment by dpatil-gmcs** [comment] 2016-07-01 13:05
@JonBrooksX @MSchirp  We have researched and made few changes, the sajari seems to load in few seconds after the page is loaded, Please have a look and let us know your views on it.

**Comment by dpatil-gmcs** [comment] 2016-07-06 08:45
@JonBrooksX  @MSchirp 

Any updates for us?

**Comment by MSchirp** [comment] 2016-07-06 16:13
Can you push this live and let me know when that is done? thanks!

**Comment by dpatil-gmcs** [comment] 2016-07-07 06:22
@MSchirp I have pushed it to LIVE site, Please have a look and give us a sign-off so that we can close the issue.

**Closed** 2016-07-07 15:16 UTC
Labels: bug, discussing, ready for review, urgent
