### ISSUE TITLE
Some Major Bugs Happening for me in Discussions

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#186] opened 2015-12-01 06:53 UTC
some weird things happening lately when i'm writing comments in the discussion forums. sometimes i am copy/pasting and my entire response disappears --- seems there's a definite problem with the copy/paste mechanism. another time part of my response just disappeared inexplicably while i was typing it. not sure what's up.

**Comment by dpatil-gmcs** [comment] 2015-12-30 14:14
Cannot reproduce this issue locally. Cannot TEST it on PROD. Can you let us know if this issue still persists and that the code deployed on the LIVE Site is EXACT replica of the PROD Branch in BeanStalk ?

**Comment by jetlej** [comment] 2016-01-02 00:16
@dpatil-gmcs - Please @mention people when you're looking for a response AND tag the issue as 'Discussing'

**Comment by dpatil-gmcs** [comment] 2016-01-04 06:19
Sure, Thanks ! Will do that henceforth ! Sorry for the inconvenience.

**Comment by lostboyevsky** [comment] 2016-01-06 10:21
yes, the issue persists. more specifics:

go into any Discussion, and try to reply to it. write out a line of text (type anything), then hit Return twice. now, try to copy and paste on the new line. it will erase everything in the text box (at least this is what happens for me in Safari on a Macbook Pro).

**Comment by dpatil-gmcs** [comment] 2016-01-07 10:18
@lostboyevsky :
Code has been checked in to PROD Branch with Commit # : 01290d47
Please let us know your comments if the issue has been fixed, that way we can CLOSE it. Thanks !

**Comment by jetlej** [comment] 2016-01-14 15:48
@lostboyevsky @MSchirp

**Comment by lostboyevsky** [comment] 2016-01-14 21:21
@dpatil-gmcs The issue persists. The same thing is still happening.

**Comment by dpatil-gmcs** [comment] 2016-01-15 06:00
@lostboyevsky @jetlej @MSchirp : 

Where are you testing the code meaning Stage / Prod ?
Are we sure that the Commit we made : Commit # : 01290d47 has been deployed to your Stage / Prod environments before you tested ?

We have no access hence cannot verify it. Let us know if the code has been deployed. Thanks !

**Comment by lostboyevsky** [comment] 2016-01-15 22:21
I just checked, and on the test site, this issue is *resolved.* However, when you push updates from the test site, does it push *everything* currently live on the test site? Because as I said in another thread a few minutes ago, the test site is currently *really messed up* for me. 

See these images:

![screen shot 2016-01-15 at 2 12 41 pm](https://cloud.githubusercontent.com/assets/9164601/12366930/3c0ca220-bb93-11e5-8abf-6150bcb6e671.png)

![screen shot 2016-01-15 at 2 10 56 pm](https://cloud.githubusercontent.com/assets/9164601/12366931/3c1075da-bb93-11e5-9092-1574c03c1757.png)

**Comment by dpatil-gmcs** [comment] 2016-01-18 06:35
@lostboyevsky : <b>However, when you push updates from the test site, does it push everything currently live on the test site? Because as I said in another thread a few minutes ago, the test site is currently really messed up for me.</b>

In context to your query, 
1. How do you deploy changes to the PROD ? : If you deploy only the DELTA (i.e.Commit # : 01290d47) from Beanstalk, then we are good to deploy. 
The Stage Site being messed up is related to some PLUGIN and we are sure that PROD and <b>Stage Site PLUGINS NOT being in SYNC.</b> Hence the issue only on Stage Site.

**Comment by lostboyevsky** [comment] 2016-01-19 20:35
@dpatil-gmcs ahhhh okay, that makes sense. BTW, i don't know the meaning of "the PROD," "DELTA," or "Beanstalk."

**Comment by dpatil-gmcs** [comment] 2016-01-21 14:41
@MSchirp : Deployed on LIVE

**Closed by dpatil-gmcs** 2016-01-21 14:41 UTC
Labels: discussing, ready for review, urgent
