### ISSUE TITLE
Homepage shows duplicate blog posts if you're logged out

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#208] opened 2016-01-05 17:02 UTC
This is the second issue in which something is visible in a different way for a logged in user than for a non-logged in user. Do you perhaps know other areas where this might be the case @jetlej ?

See screenshots:

Top 3 articles:

![screen shot 2016-01-05 at 17 58 40](https://cloud.githubusercontent.com/assets/13124056/12122433/4b7b806a-b3db-11e5-85a2-10c9da5a1139.png)

Are duplicated below:

![screen shot 2016-01-05 at 17 58 51](https://cloud.githubusercontent.com/assets/13124056/12122451/6538bf7c-b3db-11e5-9204-c99a65cb882b.png)

**Comment by dpatil-gmcs** [comment] 2016-01-06 10:31
@MSchirp : Ideally infinite scroll on Homepage should not include duplicate post.Please let us know your comments.

**Comment by dpatil-gmcs** [comment] 2016-01-06 11:17
Code has been checked in to PROD Branch with Commit # : 3ff1c3b6
Please let us know your comments if the issue has been fixed.This is partial commit, does not include infinitescroll to have ability to remove duplicate posts. Thanks !

**Comment by dpatil-gmcs** [comment] 2016-01-06 11:27
@MSchirp :
Task effort:
Task Understanding: 30 Minutes
Finding out the cause: 1.30 Minutes
Implementing: 1 Hour
Testing: 1.30 Hour

**Comment by jetlej** [comment] 2016-01-06 14:26
@dpatil-gmcs - How did this take 4.5 hours to complete? This is a 30 minute task at most. 

Even more confusing is why testing took 1.3 hours...

**Comment by dpatil-gmcs** [comment] 2016-01-07 08:44
@jetlej : This issue is NOT reproducible to us LOCALLY. Also, we had to believe the image screenshot attached to the Issue to identify the issue as it does not seem to be there on Prod / Staging for us (as we have no login credentials). 

Hence, we had to ENSURE that the code we did, would fix this issue.
The UI took us barely 15 minutes to confirm that our fix was right. However, It was not just a UI Test to ensure that a duplicate POST wasn't rendered. It involved CODE Side testing as well to ensure that the duplicate POST not be rendered when actually deployed on Stage / Prod. For that we introduced data-id attributes to ALL Posts for testing purpose (initially it was just for the first 4 Posts)...We also did a POST Dump to verify the contents fetched and displayed were UNIQUE.

**Comment by MSchirp** [comment] 2016-01-15 13:08
@dpatil-gmcs This looks to be fixed. Frontpage looks similar whether you're logged in or not. Can you confirm you pushed the fix to the live site?

**Comment by lostboyevsky** [comment] 2016-01-15 22:35
can confirm that this appears to be fixed on the live site.

**Comment by JonBrooksX** [comment] 2016-01-15 23:53
yeah, looks fine to me too

**Comment by dpatil-gmcs** [comment] 2016-01-21 14:41
@MSchirp : Deployed on LIVE

**Closed by dpatil-gmcs** 2016-01-21 14:41 UTC
Labels: discussing, ready for review
