### ISSUE TITLE
I'm seeing a weird string of code appearing at the top of many HE pages 

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#260] opened 2016-02-22 21:44 UTC
This code --- "var _sf_startpt=(new Date()).getTime()" --- seems to be appearing in the top-left corner of all blog posts and archive pages. This is quite unsightly and should be fixed ASAP.

See here:

![screen shot 2016-02-22 at 1 37 12 pm](https://cloud.githubusercontent.com/assets/9164601/13233798/59f771b2-d96a-11e5-94e0-71e55630f8e8.png)
![screen shot 2016-02-22 at 1 37 02 pm](https://cloud.githubusercontent.com/assets/9164601/13233822/6db19d04-d96a-11e5-809e-727f247a3bc3.png)

**Comment by dpatil-gmcs** [comment] 2016-02-23 07:18
@lostboyevsky @MSchirp  The issue is not reproducible on LOCAL and TEST sites, and also the string code was not visible yesterday, Can you please let us know if any one of your developers has tweek the code or played with the plugins?

**Comment by MSchirp** [comment] 2016-02-23 18:11
Hey @dpatil-gmcs , from now on you can assume no changes are made by someone else unless we explicitly tell you. We will let you know if we think we broke it. This just seemed to come out of nowhere.

**Comment by lostboyevsky** [comment] 2016-02-24 02:48
@dpatil-gmcs, that's very strange that you wouldn't see this issue, as I'm seeing it on both Chrome and Safari on both desktop *and* mobile (Macbook Pro and iPhone 5). As Martijn indicated, we **almost never** tinker with code or mess around with plugins on our end. We are not developers and do not have other developers on this end. 

Here's hoping we can resolve this one as quickly as possible. Thanks for all of your hard work.

**Comment by dpatil-gmcs** [comment] 2016-02-24 05:52
@lostboyevsky : Not sure what has caused this sudden code break. We are looking into it. BTW, when I said this issue is not reproducible on LOCAL / TEST Site, I meant there is something that has been done only on the LIVE Site. Else the code break would have appeared on LOCAL / Test Site as well. Also, it is tough for us to analyze things on PROD, however, will keep you posted.

**Comment by dpatil-gmcs** [comment] 2016-02-25 05:16
@lostboyevsky @MSchirp 
The issue is fixed now, It was caused because of the new plugin installed "Insert footers and headers",
The meta tag in the setting was not closed properly, Hence the issue.

**Closed by dpatil-gmcs** 2016-02-25 05:16 UTC
Labels: bug, discussing, urgent

**Comment by lostboyevsky** [comment] 2016-03-02 01:17
Thanks for the information, @dpatil-gmcs. Glad you figured out the source of the problem. <3
