### ISSUE TITLE
More Issues with the 'Recommendation' widget in the sidebar

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#216] opened 2016-01-14 01:06 UTC
This thing is consistently buggy in different ways. I recommend messing around with it on different blog posts to see its behavior in numerous instances. One thing it does consistently is that it won't let me scroll down past a certain number. It will seemingly arbitrarily clip the list at some point (sometimes even cutting an item in half) and won't allow me to scroll past that point. See this image:
![screen shot 2016-01-13 at 5 04 15 pm](https://cloud.githubusercontent.com/assets/9164601/12312878/ef189c3e-ba17-11e5-82ba-931c2fa4c489.png)

I was unable to scroll any farther. Note that item #5 was sliced in half.

**Comment by MSchirp** [comment] 2016-01-14 14:40
Please see issue #217 too, it is related.

**Comment by dpatil-gmcs** [comment] 2016-01-19 14:26
@lostboyevsky :
Can you give more specifics ? We cannot reproduce this issue locally. If you give us the URL where it occur it will be great. Thanks..!!

**Comment by lostboyevsky** [comment] 2016-01-19 20:32
it can happen on any blog post. there doesn't seem to be a clear reason why it happens sometimes and not other times. it's happening for me now on this post: http://highexistence.com/how-a-password-changed-my-life/

sometimes this issue is occurring immediately when i visit a blog post. other times, it occurs after i've scrolled all the way through the blog post (and down past the end-of-post recommendation widget), then scrolled back up, so you should try doing that to see if you can get the issue to happen.

**Comment by dpatil-gmcs** [comment] 2016-01-20 09:13
@lostboyevsky :
I am still not able to reproduce the issue. Please see the attached screengrab
![selection_090](https://cloud.githubusercontent.com/assets/5171153/12444240/d32e1c9e-bf83-11e5-9849-75298e78093d.png)


Time invested in trying to reproduce the issue: 20 Minutes

**Comment by lostboyevsky** [comment] 2016-01-21 22:31
@dpatil-gmcs on my screen, that scroll bar only shows up some of the time and disappears when i'm unable to scroll down. i'm trying to scroll with a Macbook touchpad, and i'm in Safari.

**Comment by dpatil-gmcs** [comment] 2016-01-27 08:59
@lostboyevsky : Any updates / steps to reproduce ? Is it happening only on your desktop (may be blocked javascript, not sure) Or is it happening for everyone ?

**Comment by MSchirp** [comment] 2016-01-27 15:42
@dpatil-gmcs I think this can be closed, it seems fixed. @lostboyevsky ?

**Comment by MSchirp** [comment] 2016-01-27 21:44
@dpatil-gmcs & @mish15 

Alright, this doesn't seem completely running as it should. 

1-3 should be most related to the current post, but it sometimes shows something completely different than related, even extremely unrelated post.
4-8 should show most popular, which seems to be happening. Although it is showing the same one again and again, even after I visited one of them already.
9-10 should show new post. But it is not showing new post at all. It is showing old, unrelated posts, again and again. See screenshot:

![screen shot 2016-01-27 at 22 39 18](https://cloud.githubusercontent.com/assets/13124056/12629278/74874afc-c547-11e5-836b-55dfa9c8f72b.png)

On top of that, it sometimes shows just 8 recommended posts, other times 9, and again other times 10. What is going on?

**Comment by mish15** [comment] 2016-01-27 22:12
We'll take a look at the logs and see what is happening. Mixing different
units may be the issue, as they aren't aware of the others, etc. we'll look
at this today and come back with some feedback.


On Thursday, 28 January 2016, Martijn Schirp <notifications@github.com>
wrote:

> @dpatil-gmcs <https://github.com/dpatil-gmcs> & @mish15
> <https://github.com/mish15>
>
> Alright, this doesn't seem completely running as it should.
>
> 1-3 should be most related to the current post, but it sometimes shows
> something completely different than related, even extremely unrelated post.
> 4-8 should show most popular, which seems to be happening. Although it is
> showing the same one again and again, even after I visited one of them
> already.
> 9-10 should show new post. But it is not showing new post at all. It is
> showing old, unrelated posts, again and again. See screenshot:
>
> [image: screen shot 2016-01-27 at 22 39 18]
> <https://cloud.githubusercontent.com/assets/13124056/12629278/74874afc-c547-11e5-836b-55dfa9c8f72b.png>
>
> On top of that, it sometimes shows just 8 recommended posts, other times
> 9, and again other times 10. What is going on?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jetlej/HE-6.0-Bugs/issues/216#issuecomment-175871391>.
>


-- 
*Hamish Ogilvy*
Sajari Pty Ltd
L2, 50 Bridge St, Sydney, NSW 2000 Australia
*t:  +61 (*0) 414 658 353  |  *e: *hogilvy@sajari.com
*w:*  www.sajari.com

**Comment by mish15** [comment] 2016-01-27 23:25
@MSchirp ok so we've seen a change from using almost 100% "related" to using an even mix of "best", "popular" and "recent".

So quick notes:
- [ ] 1-3 should be switched to "related", instead of what it is using currently (prob "best")
- [ ] We order by date discovered if we can't find a date, so it may be better to order by "post-id" or something else? the guys have done a good job adding in custom meta, so if we could also get a post timestamp, or sort by ID desc, that will work better than "the date we first found the content". Thoughts @dpatil-gmcs ?
- [ ] We don't hide things people have clicked on already, but this is an active request in dev, i'll try to get it expedited for you.

**Comment by lostboyevsky** [comment] 2016-01-28 04:50
@MSchirp, no, the original issue isn't fixed for me. it's still happening, along with the other issues you've highlighted. 

@dpatil-gmcs, i don't know if my issue is happening for anyone else. i can try to use HE on someone else's laptop or desktop and see if it does the same thing. i will try to do that and get back to you

**Comment by mish15** [comment] 2016-01-28 05:16
@lostboyevsky regarding the clipping, yeah it's inside a fixed height container or something. Not sure, but it prob should be fluid. I've noticed this means it can't scroll in some situations either, which would be the same containing CSS (e.g. the overflow is hidden, so this is scrolling separate to the page).

**Comment by MSchirp** [comment] 2016-01-28 11:15
Thank you for your comments @mish15 ! Glad to have that option expedited! 

Could you tell me the difference between related and best? 
Any idea why it sometimes shows 8, other times 9, and again other times 10? (I know one reduction happens happens when you view an article that is also in the recommended list. Is it possible to add a rule that when this is the case, it ads an extra one?)
Also do you have an idea why the bottom 2 are the same one all across the board?

**Comment by mish15** [comment] 2016-01-28 11:34
@MSchirp no problem! Quick answers:
- "best" is individual, based on articles you've engaged with previously, popularity, recency, locality all bundled together. But what you've engaged with will dominate, so this looks the same page to page as it doesn't care about the current page, but it will be different for all users.
- "related" looks to find content similar to the current page
- I think the 8, 9, 10 is related to the container it's being rendered in. All three requests are asking for 10 results each, so there's more than enough to fill 10 slots.
- I would guess the bottom two are the same because this is looking at popular, popularity changes at a slower pace, so these remain pretty stable and are not related to the current pages content. If the ones you had seen were hidden it would make more sense as they would rotate for each user, we're on it.

**Comment by dpatil-gmcs** [comment] 2016-02-02 06:46
@lostboyevsky @MSchirp 
My Understanding from the above comments:
Our current implementation for the posts is:
1 - 3 : Best
4 - 7 : Popular
8 - 10 : Recent
and you want to modify it as:
1 - 3 : Related
4 - 7 : Popular
8 - 10 : Recent.

Please let me know if we both are on the same track, so that I can proceed with the implementation of the change.

**Comment by mish15** [comment] 2016-02-02 06:52
@dpatil-gmcs yes, correct. Also, is it possible to allow the container to overflow so the recommendations are not cut off?

**Comment by dpatil-gmcs** [comment] 2016-02-02 11:29
@lostboyevsky @MSchirp  As per the discussion with @mish15, I have updated the code, so now the Recomendation widget will show the posts as follows:
1 - 3 : Related
4 - 7 : Popular
8 - 10 : Recent
The change is commited to the PROD branch with the commit# : ac1b4911
Changes are deployed on Test Site. Please verify and let us know that way we deploy changes to LIVE.

**Comment by dpatil-gmcs** [comment] 2016-02-02 14:41
@MSchirp @mish15 : Deployed changes on LIVE. Please verify that way we close this issue. Thanks !

**Comment by mish15** [comment] 2016-02-03 02:16
@dpatil-gmcs yes "best" is now related. Thanks for this, this is great.

Couple of quick ones:
- [ ] The container with the recommendations is still cutting off (sometimes there are only 9, sometimes less, but each recommendation returns 10 results)
- [ ] Can you please add `.meta('category', categoryName)` to each of the requests, where categoryName is the category of the current page
- [ ] Can you please add `.meta('post-id', postId)` to each of the requests, where postId is the ID for the current page

e.g. 
```
SJ.Recommend('recent').filter('post-type','=','post').meta('category', categoryName).meta('post-id', postId).run(...
```

**Comment by dpatil-gmcs** [comment] 2016-02-03 10:29
@mish15  
1. How do we pass the categories, in case a post is associated with multiple categories?
2. Also do you want meta tags for other two('Popular' and 'recent') as well?

**Comment by mish15** [comment] 2016-02-03 11:10
1. You can use a semicolon as delimiter
2. Yes please

Thanks!

On Wednesday, 3 February 2016, dpatil-gmcs <notifications@github.com> wrote:

> @mish15 <https://github.com/mish15>
>
> 1. How do we pass the categories, in case a post is associated with
> multiple categories?
> 2. Also do you want meta tags for other two('Popular' and 'recent') as
> well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jetlej/HE-6.0-Bugs/issues/216#issuecomment-179153185>.
>


-- 
*Hamish Ogilvy*
Sajari Pty Ltd
L2, 50 Bridge St, Sydney, NSW 2000 Australia
*t:  +61 (*0) 414 658 353  |  *e: *hogilvy@sajari.com
*w:*  www.sajari.com

**Comment by dpatil-gmcs** [comment] 2016-02-03 13:28
@MSchirp  @mish15 
I have made the recommended changes and also fixed the container issue, Now the container must always show 10 posts. The changes are commited to the PROD branch with the commit#: b7cebe2a.
Please have a look, and let us know your comments on it.

**Comment by MSchirp** [comment] 2016-02-03 17:18
Just go ahead and publish it live @dpatil-gmcs 

@mish15 How are the recent ones determined? It still consistently shows the same articles, and they are neither related, nor best, nor popular, nor recent. Please advise!

**Comment by mish15** [comment] 2016-02-03 22:04
@dpatil-gmcs the content still gets trapped for me. I'm using chrome on OSX. See screenshot below. Also i still only see a max of 9 posts?

![screen shot 2016-02-04 at 8 40 03 am](https://cloud.githubusercontent.com/assets/869412/12797994/1a5b8aa0-cb1b-11e5-9883-d384edf870f3.png)

Also, i'm not seeing the meta changes, so i'm guessing your changes are not in prod yet?

@MSchirp please see above comments on "recent", and why sending the post-id with the request is the likely solution in the short term (pending implementation at your end, once these changes are in prod we can make changes)

**Comment by dpatil-gmcs** [comment] 2016-02-04 07:03
@MSchirp @mish15 
I have deployed the changes on the LIVE site. Now you will be able to see the changes on LIVE too.

**Comment by MSchirp** [comment] 2016-02-04 14:21
@mish15 @dpatil-gmcs 

I just published a new blog post, and related shows 3 of the same series of articles. See screenshot: 

![screen shot 2016-02-04 at 15 08 13](https://cloud.githubusercontent.com/assets/13124056/12817461/64797f70-cb52-11e5-883f-fb6919af6d9d.png)

Is there a way to prevent this from happening? (same happens in the popular group, where it shows part 1 and III of our movies articles at the same time.) Can we exclude posts if, say, 70% of the title overlap? 

Just checked the 'recent issue' regarding number 9 and 10. They still show the same two posts that aren't recent. See screenshot:

![screen shot 2016-02-04 at 15 21 32](https://cloud.githubusercontent.com/assets/13124056/12817578/ffabbdd2-cb52-11e5-8ef9-914dc0a5ce2e.png)

**Comment by mish15** [comment] 2016-02-05 00:45
@MSchirp they look pretty well related! :) Just kidding. Yes you can do this by:
- [ ] passing the series ID (do you have this?) in the HTML (data-sj-meta-seriesId=123)
- [ ] add a filter to the query to remove those with the current page's series ID. e.g. `.filter('seriesId', '!=', 123)`

Re: recent. @MSchirp yes we are aware, need to implement my comment above, look for `scales=post-id,1000000,1000000,5,0`. @dpatil-gmcs "recent" can actually be replace with a "search" that favours the current category also, e.g. 
```
SJ.Query()
  .scale('post-id',1000000,1000000,5,0)
  .filter('post-type','=','post')
  .meta('category','Philosophy;')
  .meta('post-id','368915')
  .run(successCallback_best,failureCallback_best);
```

Note: this can also use the filter, once a series ID is being indexed

**Comment by dpatil-gmcs** [comment] 2016-02-10 05:17
@MSchirp  As @mish15  wants us to pass the series ID, in order to not have posts with same series listed under, "Related Posts" just an FYI we are not maintaining any series ID at our end, we may have to look for a plugin to achive this. Looking into this.

**Comment by dpatil-gmcs** [comment] 2016-02-10 09:01
@mish15  We are looking for a plugin which will associate a series id to any given post (to Group posts with series). Assuming we do that, will sajari response ensure that related posts have unique series ID.
Example : 

Assuming every POST has a Series ID associated to it. And User visits "PostPage1" URL with Series "S1"
We alter the code as follows : 
SJ.Recommend('related')			
			.filter('seriesID', '!=', '123')
            .filter('post-type', '=', 'post')
            .meta('category', 'catID')
            .meta('post-id', 'postId')
            .run(successCallback_best, failureCallback_best);
			
What will Sajari do : 

1. I am sure Sajari will return posts NOT in Series ID = 123. Assume Sajari returns posts from Series ID = 234, 345,.....et.al.
What if SID = 345 has multiple posts in it ? Ideally Sajari should return 1 Post from each Series ID right ? That way we get over the issue we saw above : Same Series Posts listed under Related Posts

2. What if a given Post has no series id associated to it ? Meaning are there chances of reproducing the issue we reported above : Same series listed under "Related Posts" ?

3. If #2 is an issue, then we must ensure every POST has a Series ID associated to it ?

@MSchirp  If the above stated makes sense to @mish15 , then you should take care of grouping posts to appropriate Series. Pluging allows us to create as many series as we want, and to assign only one series to a particular post.


**NOTE : **
The above discussed code is applicable only to POST TYPE "POST" : http://highexistence.com/13-brilliant-and-hilariously-subversive-people-to-follow-on-twitter/ 
and not "Quotes" http://highexistence.com/quotes/view/369476/ where we show Sajari recommendations.

@MCShirp : For Quotes Page, we still show Posts in Sajari Recommendations and not quoes.So is it LOGICAL to group quotes with Posts ? The obvious question since Quotes and Posts are 2 different things.

**Comment by dpatil-gmcs** [comment] 2016-02-10 10:34
@MSchirp  @mish15 
The code is committed to the PROD branch with the commit# : 419f2335,

Our code and plugin (to group posts with series ID) is deployed on Test Site. As the sajari recommendations on Test Site point to the LIVE site, we are unable to test it as Test Site Sajari recommendations come from Stage and not from LIVE.

@MSchirp : Can we have Test Site Sajari recommendations come from Stage and not from LIVE ? OR do you want us to deploy code to LIVE Site directly, where you will have to set Series to all posts logically. (We cannot do that as we have no domain knowledge and we wouldn't know to LOGICALLY co-relate Posts).
NOTE : 
1. Our implementation will NOT WORK until @MSchirp associates Series to posts.
2. For "Quotes" page, we have NOT implemented anything yet. As we are awaiting @MSchirp  answer on the query we mentioned above.

@mish15 : We are also awaiting your reply on the same. Thanks !

@MSchirp : We are about to deploy our changes to Live Site, however they will not be in action until series id are associated to posts. So deploying our code will not cause regression breaks.

**Comment by mish15** [comment] 2016-02-10 22:54
@dpatil-gmcs your query looks good. Responses to your points:

1. It filters out those matching the filter. It is not a "return only one of these" type operation, so if another series has two posts that match, they will be in the recommendations. I think this is normal behaviour.

2. If there is no series ID, but it is a series of the same content, as far as we can detect it will be related (which is true). So a missing series id won't be filtered out.

3. No i don't think so. It's really only needed for posts that are in a series and you want to filter out the same series. Others don't need it.

@dpatil-gmcs it is difficult to test staging as normally we can't index it. However, if you want to create a new staging collection and allow requests from our crawler (header user-agent has "Sajaribot"), then we can get that setup. The difficulty typically is that because it isn't live, we don't get usage, so it's tough to know what is popular, new, etc. But it is doable.

**Comment by dpatil-gmcs** [comment] 2016-02-11 05:27
@mish15  @MSchirp 
We have our code and plugin already deployed on LIVE, However, the logical grouping viz associating series ID to posts needs to be done by @MSchirp after which we can see our code in action.

@mish15  Just to confirm from your above explaination, there are still 2-5% chances of similar series being listed in recommendations? Also they need to logically grouped.

**Comment by mish15** [comment] 2016-02-11 06:12
@dpatil-gmcs not sure about 2-5%? We don't group results currently. But note: you request 10 items and only use 3-4, so you could filter other series groups client side if it is important. I don't think you'll gain much though.

**Comment by dpatil-gmcs** [comment] 2016-02-12 07:18
@mish15  I agree, once @MSchirp  logically groups posts on the live site, we will be able to see the response coming from sajari, and modify our logic to avoid this  2-5% chances of similar series being listed in recommendations. Does this make sense?

**Comment by MSchirp** [comment] 2016-02-12 13:49
@dpatil-gmcs @mish15 

I just added a few series as per your suggestions
and now the widget stopped working
I just removed all series again, but its not fixed

**Comment by dpatil-gmcs** [comment] 2016-02-12 14:25
@MSchirp @mish15 : Seems like Sajari had some issues...We now see recommendations without any tweaks. Please confirm. Thanks !

**Comment by dpatil-gmcs** [comment] 2016-02-12 14:38
@MSchirp : Please start assigning Series logically to Posts. And let us see how Sajari responds. That way we write our parsing logic in success callbacks to AVOID repeated posts just in case.

**Comment by MSchirp** [comment] 2016-02-12 15:44
All series are added.

**Comment by mish15** [comment] 2016-02-15 01:54
ok great. The reindex frequency is ~1week max. So i will flush this index and rebuild the whole thing to pick up all the series information, then review the changes, standby. 

@dpatil-gmcs we had a failure on friday for ~20 minutes. The system was up, but not responding normally to some requests (search, recommend, profiling). Our guys were alerted to it instantly, but it took 20 min to fix (it was 1am friday night here). We found the issue and pushed a new version on saturday to make sure it doesn't happen again. First outage in over 6 months, annoying! Apologies for any inconvenience!

**Comment by mish15** [comment] 2016-02-15 19:01
@dpatil-gmcs i flushed and did a full recrawl, but i'm not seeing the sequence coming through on any pages. Is this being passed into Sajari meta?

**Comment by dpatil-gmcs** [comment] 2016-02-26 05:55
@mish15 Yes, you won't get any sequence id, Untill @MSchirp  associates the sequence to the posts,
@MSchirp  Can you please do the needfull?

**Comment by MSchirp** [comment] 2016-02-27 17:57
@dpatil-gmcs I added all the series as per your instructions 15 days ago. Go to posts -> series and you will find all series and posts.

**Comment by MSchirp** [comment] 2016-02-27 17:58
Recommended blog posts nr 9 and nr 10 are still showing the same one over and over again.

See screenshot:

![screen shot 2016-02-27 at 18 57 38](https://cloud.githubusercontent.com/assets/13124056/13374399/13078f9e-dd84-11e5-8658-7fccf89d3bf1.png)

**Comment by mish15** [comment] 2016-02-28 01:34
@MSchirp we have an update in testing to rotate out clicks and also to change the popularity vector (currently the time is too long, so changes are very slow to happen). Both changes are expected this week.

@dpatil-gmcs we're still not seeing a sequence ID coming through. Please advise when this is live so we can get that sorted.

**Comment by dpatil-gmcs** [comment] 2016-02-29 05:42
@MSchirp @mish15  Yes, @MSchirp  has assigned the sequence ID to some posts, but not all the posts, so only for those posts which have sequence ID assigned will give you sequence ID, if the sequence ID is not assigned it will not send any.

**Comment by mish15** [comment] 2016-02-29 21:18
@dpatil-gmcs we can list all meta params passed and haven't seen one yet, so i think it may not be being passed to us? Below are the meta keys being added currently. Mostly they are internal. I see some that you are adding: "post-id", "post-type", "featimage", but nothing to do with sequence. Our guys are checking this periodically. Any ideas?

```
"keys": {
                "badmeta": "",
                "boost": "",
                "canonical": "",
                "category": "",
                "count": "",
                "date": "",
                "description": "",
                "dir1": "",
                "dir2": "",
                "exDate": "",
                "exEmail": "",
                "exPhone": "",
                "exSummary": "",
                "featimage": "",
                "firstseen": "",
                "image": "",
                "post-id": "",
                "post-type": "",
                "project": "",
                "title": "",
                "url": ""
            }
```

**Comment by dpatil-gmcs** [comment] 2016-03-01 11:15
@mish15 @MSchirp  As I said yesterday, all the posts are not assigned series id, so only those posts which has series id will send you a 'seriesId' parameter.
e.g: http://highexistence.com/entering-the-caves-of-the-unconscious-a-story-of-crossing-the-threshold-on-the-heros-journey/ is assigned with a series, so the above mentioned post must send you seriesId = 16043

Can you please try to check with the above url.

**Comment by mish15** [comment] 2016-03-01 22:47
@dpatil-gmcs i can see you send the seriesId as a filter in the query, but this data is not making it into Sajari, so it won't have any effect. You pass in other data, e.g. `<meta data-sj-meta-post-type content="post"/>`, but seriesId is not present on any page thus far, so we can't query it. The query looks fine, it's the meta we need to get it working!

**Comment by dhowden** [comment] 2016-03-03 06:06
@MSchirp  Just deployed a big update to our popularity API which now returns near-real time results (i.e. on a minute-by-minute basis, rather than the more long-term measure we used before).

**Comment by dpatil-gmcs** [comment] 2016-03-03 14:33
@mish15 @MSchirp  So do you want us to send the series-Id as meta?

**Comment by mish15** [comment] 2016-03-03 21:21
Yes. Thanks

**Comment by dhowden** [comment] 2016-03-04 06:00
@MSchirp @dpatil-gmcs Just noticed that you are actually searching for the term `search` which will significantly skew the results:
```javascript
            function successCallback_popular(r){
                if(r != null){
                    successCallback(r,4);
                }
                /*SJ.Recommend('recent')
                .filter('post-type', '=', 'post')
                .run(successCallback_recent , failureCallback_recent);     */
                SJ.Query('search')
                    .scale('post-id',1000000,1000000,5,0)
                    .filter('post-type','=','post')
                    .meta('category','Random + Awesome;')
                    .meta('post-id','371096')
                    .run(successCallback_recent , failureCallback_recent);
            }
```

You probably want to use this instead:

```javascript
SJ.Query().scale('post-id',1000000,1000000,5,0)
                  .filter('post-type','=','post')
                  .meta('category','Random + Awesome;')
                  .meta('post-id','371096')
                  .run(successCallback_recent , failureCallback_recent);
```
instead.

**Comment by dpatil-gmcs** [comment] 2016-03-04 07:20
@dhowden  We have made the change as per your recommendation, Please have a look.

**Comment by dpatil-gmcs** [comment] 2016-03-04 07:22
@mish15 @MSchirp  We have added the series Id as meta tag. so now you will receive a tag just like <meta data-sj-meta-series-id content="123"/> where series id is present, If series Id is not present the content field will be empty.

**Comment by MSchirp** [comment] 2016-03-04 14:32
@dhowden Thanks David, that is awesome! Quick question, how do you guys measure popularity? Im seeing an article that shouldn't be on there and I am wondering what the cause might be.

@mish15 Thanks again for all your help, its been fantastic!

**Comment by dhowden** [comment] 2016-03-04 21:05
@MSchirp It tracks which pages are being viewed over a period of a few minutes and then computes a popularity score from that.  Which article shouldn't be in there - I can check it out.

**Comment by mish15** [comment] 2016-03-06 10:08
@MSchirp no problem, we're getting closer now! FYI: We have another JS release that is very close,  this will filter out anything clicked in the current session. So you won't see something that has been clicked on already again in the recommendations.

@dpatil-gmcs we're now seeing the series id coming through, but note it's coming through as "series-id", but the query is using "seriesId", which will not match. Can you please change the query to use "series-id" also?

**Comment by dpatil-gmcs** [comment] 2016-03-07 05:27
@mish15  Made the required change, now you must get "series-id".

**Comment by mish15** [comment] 2016-03-07 21:19
@dpatil-gmcs great that works! One more thing. Please see my comment from feb 5th above, the "series-id" should be a filter in the request, not sent as meta, e.g. 

- [ ] add a filter to the query to remove those with the current page's series ID. e.g. .filter('seriesId', '!=', 123)

**Comment by MSchirp** [comment] 2016-03-08 13:17
@mish15 That filter would be great, awesome job guys :)

**Comment by dpatil-gmcs** [comment] 2016-03-08 14:02
@mish15 @MSchirp  We have added filter to the query.
NOTE: The posts which do not have series-Id, we are sending series-id as 0, will it be ok for sajari or should we change the value to negative or must we pass blank value?

**Comment by mish15** [comment] 2016-03-09 00:17
@dpatil-gmcs that will work! Let's monitor and see how it goes. 

@MSchirp if you have any tests you want  to run let us know what you see? I think @dhowden was waiting for some feedback on his popularity comments

**Comment by MSchirp** [comment] 2016-03-10 11:44
@mish15 Could you elaborate? I am not sure if I understand your question, thanks :)

**Comment by dhowden** [comment] 2016-03-10 11:58
> @dhowden Thanks David, that is awesome! Quick question, how do you guys measure popularity? Im seeing an article that shouldn't be on there and I am wondering what the cause might be.

@MSchirp Are you still seeing this?  If so, which article?

**Comment by MSchirp** [comment] 2016-03-10 12:10
@dhowden Actually, no. I haven't been seeing this. But I haven't really checked either. Will keep an eye out and let you know if something strange happens.

**Closed** 2016-04-23 16:09 UTC
Labels: bug, discussing, ready for review
