### ISSUE TITLE
Add @mention tags to comments

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#34] opened 2015-07-14 21:09 UTC
This feature is on hiexistence.com, I think it will bind the community if we could do this here! Great way to share within HE.

**Comment by jetlej** [comment] 2015-07-16 01:09
hiexistence.com is a clone of HE. There's no way it's on that site and not on the live site. Screenshots?

**Comment by JonBrooksX** [comment] 2015-07-16 01:46
I searched everywhere for this! I knew I saw it! 

![screenshot 2015-07-16 02 45 40](https://cloud.githubusercontent.com/assets/13107838/8713775/d9bade2a-2b64-11e5-9ee5-6c938da172ce.png)

**Comment by jetlej** [comment] 2015-08-25 22:25
Apparently that's just copy/pasted html. Still, this feature is doable. I'll make it an enhancement :)

**Comment by jetlej** [comment] 2015-08-29 01:15
To do this right, we need to integrate notifications when someone is mentioned, and some kind of awesome auto-fill thing that shows the usernames they can choose from as they type. Out of my pay grade, so will have to wait for an outside dev.

**Comment by MSchirp** [comment] 2015-09-02 10:10
Is there a way to postpone features/bugs instead of closing them?

**Comment by jetlej** [comment] 2015-09-09 18:12
@MSchirp - Unfortunately no, so I'm just labeling them as 'cantfix' and then I just filter the open issues by label when I'm going through them

**Comment by jetlej** [comment] 2015-09-09 18:12
Whoops, did not mean to close this one

**Comment by MSchirp** [comment] 2015-09-26 12:00
We will have about 1500$ saved next month, is this something we want to invest in? @JonBrooksX @lostboyevsky @jetlej

**Comment by jetlej** [comment] 2015-09-26 21:30
How active are the comments on blog posts? Not sure if this is worthwhile compared to the myriad of other things to invest in (like prototypes of the physical product ideas)

**Comment by lostboyevsky** [comment] 2015-09-26 22:25
yeah i don't think this is important enough to warrant a significant investment of any kind at this point.

**Comment by MSchirp** [comment] 2015-09-27 13:53
noted

**Comment by JonBrooksX** [comment] 2015-10-11 23:43
@jetlej @MSchirp @lostboyevsky You can tag people on literally every commenting platform I know. I do think this would improve the health of discussions. I constantly want to tag you guys in items. Imagine slack or FB or github without tagging... But if the cost is too high then maybe we should postpone it. I do think it's important though.

**Comment by lostboyevsky** [comment] 2015-10-12 19:30
i agree that it's potentially a valuable feature that we should table for now and consider investing in sometime down the line when we have taken care of the bigger fish we're currently frying.

**Comment by lostboyevsky** [comment] 2016-01-06 10:27
@dpatil-gmcs do you think you can make this happen? i agree that it would be really really nice to have.

@MSchirp

**Comment by MSchirp** [comment] 2016-01-27 16:08
@dpatil-gmcs This is one of the enhancements we think is needed the most!

**Comment by dpatil-gmcs** [comment] 2016-03-02 13:54
@MSchirp  The feature of tagging users is available in the buddypress plugin, But I think as we have customised the plugin code the autosuggest feature is not working, I will need to deep dive into our custom code for Buddypress and find out the way to implement the auto suggest feature.

**Comment by MSchirp** [comment] 2016-03-02 15:49
I've actually been thinking about this, and the notification system needs a big overhaul too. People are now notified to ALL replies of topics they once replied to. This should be turned off:

Users should only receive a notification when:
- They are tagged
- A new reply to a topic which they started (not just replied!)
- A direct reply to their comment

**Comment by lostboyevsky** [comment] 2016-03-02 21:30
@MSchirp totally agree. that would be great. it would also be awesome to have the option to unfollow certain threads that you may have started months or years ago and don't want to see notifications for anymore.

**Comment by dpatil-gmcs** [comment] 2016-03-04 12:51
@MSchirp  Any updates for us?

**Comment by dpatil-gmcs** [comment] 2016-03-08 14:00
@MSchirp  We have implemented the autosuggest mention to the TEST site comments. Now you should be able to TAG any users with the @ tag. Please have a look and let us know your thoughts on it.

We need to add the activity component of Buddypress plugin, in order to achive the functionality, Which in turn adds Activity menu in the users profile. Let us know if you want to keep the activity profile or remove it?

**Comment by MSchirp** [comment] 2016-03-10 12:39
Awesome, this is going somewhere!

- Please add an option to tag a person directly. Directly left to the 'reply' button should be a (green and strong) button saying '@username', in which username is the actual username of the user. This also opens the reply box, but the only different is that the @username is already filled in.

See screenshots:

![screen shot 2016-03-10 at 13 33 32](https://cloud.githubusercontent.com/assets/13124056/13669665/3bb0c812-e6c5-11e5-8720-3d3f0b32f091.png)
(new tag button between trash and reply. Note that I am seeing trash because I a moderator. Normal users won't see that.)

Result:
![screen shot 2016-03-10 at 13 38 09](https://cloud.githubusercontent.com/assets/13124056/13669690/5e7437e4-e6c5-11e5-81ec-fb7151c5dcd4.png)

------------

This new feature should be implemented at the same time of the notification system update. Namely:

A person should receive a notification update when, and only when:

- They are tagged
- A new reply to a topic which they started (not just replied!)
- A direct reply to their comment

**Comment by dpatil-gmcs** [comment] 2016-03-15 13:32
@MSchirp  
1. We have implemented the Green Tag button as per your requirement and committed the code to the TEST site.
While testing we found that there are some users on the site which are not registered with HE, we won't be able to tag the users whuch are not present on HE, hence we hide the tag button for such users.
Please have a look and let us know your views on it.

2. To send the email notification, we use the BuddyPress notifications, to users needs to go to settings and select the notifications the want to get via email.
Following are the steps to update the settings:
a. Click the user avatar in the menu.
b. Go to settings
c. Select Email option and update the settings.

Please have a look at it, and let us know your views on it, In that way we can pust it to LIVE site.

**Comment by MSchirp** [comment] 2016-03-15 14:03
@dpatil-gmcs 

- Could you show me users that are not registered with HE? Where are they registered instead?
- The notification shouldn't be e-mail. They should be in the notification system. See screenshot:
![screen shot 2016-03-15 at 15 00 28](https://cloud.githubusercontent.com/assets/13124056/13780208/c448ea9a-eabe-11e5-8bcb-9de07b0e61c4.png)
- Right now, a user doesn't get a new notification when the user is tagged. Please look at the updated notification rules (which shouldn't apply to e-mail, just the 'in site system'.
- The text of @username should be green. Not the background. Please use '#00c194' for the color.

**Comment by dpatil-gmcs** [comment] 2016-03-16 12:44
@MSchirp 

We have made the text of @username green and removed the green background, as per your requirement.
The code is committed to TEST site.

I the notification system that we are using is buddypress notification system. And as we have overwritten the buddy press plugin, I will have to investigate the code to make it working, Which may take time.

The email notifications can be turned on and off by the users. The steps to edit email notifications are : 
1. Click the user avatar and select settings option.
![settings](https://cloud.githubusercontent.com/assets/5171153/13812202/c1686eda-eba0-11e5-861f-d87a88246d41.png)


2. On settings page select the email option
![email](https://cloud.githubusercontent.com/assets/5171153/13812224/ec3baec4-eba0-11e5-9637-afc517aef8e8.png)

3. On the email page, user can edit the email notifications settings.
![email_notifications](https://cloud.githubusercontent.com/assets/5171153/13812231/f8429c64-eba0-11e5-9eaa-2b0fceddcc41.png)


For the users not registered/available on HE,
On the following post http://hiexistence.com/a-true-story-about-adversity-violence-and-the-importance-of-role-models/

The first comment that is visible is by JAKE, and the user is not present in our database.
I think the user might be deleted. For such users @username option is hidden.

Please let us know your views on it.

**Comment by MSchirp** [comment] 2016-03-16 14:45
Deleted users is fine, not a problem,
If e-mail notification can be turned off, that is not a problem either.

What is important is that the notification system works to the rules I wrote earlier.

**Comment by dpatil-gmcs** [comment] 2016-03-17 13:43
@MSchirp  For the notifications system, we are using Buddypress notifications. I am debugging the code locally and trying to find out the reasons, why the notifications are not shown after the user is mentioned.

**Comment by MSchirp** [comment] 2016-03-21 14:00
@dpatil-gmcs We use a custom made plug in for notifications, did you know this?

**Comment by dpatil-gmcs** [comment] 2016-03-21 14:14
@MSchirp  Ooh, so all my hours invested are wasted!
That was my intent behind asking you this question, Could you please give me details for that plugin?

**Comment by dpatil-gmcs** [comment] 2016-03-22 14:18
@MSchirp  We are able to send the notifications, on our local site. there are some minor changes left so we have not yet deployed the code to LIVE.

**Comment by MSchirp** [comment] 2016-03-22 15:15
Ok, push to test when its done! :)

**Comment by dpatil-gmcs** [comment] 2016-03-23 14:04
@MSchirp  We have implemented the notifications and deployed the code to TEST site.
However, In order to display comments, the Activity tab in user profile must be shown Please look at the screen shot attached.
![mention_notifications](https://cloud.githubusercontent.com/assets/5171153/13987515/e8f0b9fc-f12d-11e5-92d5-fe7ee69e939e.png)

Also there are some changes left, for that we will need to dive into buddypress activity module and write the code. Please have a look and let us know your views on it!

**Comment by MSchirp** [comment] 2016-03-23 14:10
@dpatil-gmcs I am not sure if I understand what you mean by "However, In order to display comments, the Activity tab in user profile must be shown". Can you elaborate?

**Comment by dpatil-gmcs** [comment] 2016-03-24 05:21
@MSchirp  On the user profile page, where we have nav buttons as "Overview", "History" and "Favourites", the "Activity" option will be added to the list. Please refer to above screen shot for reference.

**Comment by MSchirp** [comment] 2016-03-24 09:18
@dpatil-gmcs Why is that? Is it necessary?

**Comment by dpatil-gmcs** [comment] 2016-03-24 09:21
@MSchirp  Yes it is necessary to show users mention details.

**Comment by MSchirp** [comment] 2016-03-24 09:23
Could you explain why?

**Comment by dpatil-gmcs** [comment] 2016-03-24 13:49
@MSchirp  We have implemented and TESTED the task on LOCAL, now the mention notifications are visible to the user. We have deployed the code to the TEST site, but as per our discussion there is some Google analytics error on TEST site so you won't be able to test it. I have attached the screenshots please have a look.

![notifications](https://cloud.githubusercontent.com/assets/5171153/14018533/54061d9c-f1f4-11e5-88ac-6c96f6bfedb8.png)

We have also found a way so that the activity tab from the users profile page can be removed.
![userprofile](https://cloud.githubusercontent.com/assets/5171153/14018737/40e95160-f1f5-11e5-86ca-8cd547616838.png)


Please let us know your views on it.

**Comment by MSchirp** [comment] 2016-03-24 16:29
@dpatil-gmcs 

I just wanted to know why it was necessary, but now I actually understand why. Could you place the 'activity' tab back in the profile and name it 'Notifications'? Is my assumption correct that this tab is only visible to the user himself/herself?

What do you mean by google analytic error? What am I unable to test right now?

**Comment by dpatil-gmcs** [comment] 2016-03-25 13:45
@MSchirp  Renamed 'Activity' tab to 'Notifications', The code is committed to the TEST site. Please have a look.

By Google Analytics error, I can see some error in console of TEST site, which is regarding Google analytics script injected. Remember we had talk about it yesterday on slack?

Because of the above error, I think that the notifications are not been shown on TEST site.
We will have to investigate where the code is injected from.

**Comment by dpatil-gmcs** [comment] 2016-03-28 13:52
@MSchirp  We have made the changes, and implemented the code. The code is committed to the TEST site.
Please refer to the following screen shots:

1. User Profile page:
![notification_screen](https://cloud.githubusercontent.com/assets/5171153/14079190/8929ae94-f519-11e5-868d-63722a24cb15.png)


2. Notification:
![comment](https://cloud.githubusercontent.com/assets/5171153/14079182/7b63dc1c-f519-11e5-9baa-cd9b86aab994.png)

Please let us know your views on it.

What remains is to show the notification in the notification bar. It is working on local but because of some problem on TEST site, We are unable to see the top bar notifications on TEST site.

**Comment by MSchirp** [comment] 2016-03-29 10:07
@dpatil-gmcs 

- The notification page should be private (not visible to other users besides yourself)
- The What's new and post update form/button should be removed. 
- And updates should be removed in the drop down menu
- The notifications page should have the same format as the History page
- A user should also get a notification when the user received a new message

**Comment by dpatil-gmcs** [comment] 2016-03-30 14:05
@MSchirp  The first two points are implemented and the code is committed to the TEST site.
Now
1. The notification page is private, so users cannot see notifications of any other user.
2. The What's new and post update form is removed.

The updates can be removed from the drop down menu only through the plugin file, Editing plugin files is not a good idea, So I am finding a way to override the setting and hide it.

By 'A user should also get a notification when the user received a new message', Do you mean you want to show user's notification  when ever they get direct message?

**Comment by dpatil-gmcs** [comment] 2016-03-31 13:44
@MSchirp  First 4 points are implemented and the code is committed to the TEST site.
I have attached the image of the new notifications UI. Please have a look and let me know your views on it.

![notificationsui](https://cloud.githubusercontent.com/assets/5171153/14177592/a0d44524-f774-11e5-9a93-f9128f7e5114.png)


Also, Please let me know by 'A user should also get a notification when the user received a new message' do you mean you want to show notification for private messages?

**Comment by MSchirp** [comment] 2016-04-01 17:37
@dpatil-gmcs 

Are you sure you pushed changes to Test?

- I can still see notifications of other users
- the lay out is still messed up
- I can still see update form and button

**Comment by dpatil-gmcs** [comment] 2016-04-04 12:48
@MSchirp  Yes the changes are pushed to the TEST site, These changes are not visible because @jetlej  has asked beenstalkaap to change the branch on the TEST site to a branch other that PROD branch, for the issue #247.

As soon as the branch is switched back to PROD you will be able to see the changes.

**Comment by MSchirp** [comment] 2016-04-11 16:08
@dpatil-gmcs Please contact @jetlej so we can see the changes on TEST so I can confirm changes and we can push to live.

**Comment by dpatil-gmcs** [comment] 2016-04-12 12:59
@MSchirp  Yes I have asked @jetlej  to change TEST site back to PRODUCTION branch so that you can have a look an confirm.

**Comment by MSchirp** [comment] 2016-04-13 16:11
Alright, please notify me on slack when this is done.

**Comment by dpatil-gmcs** [comment] 2016-04-19 13:59
@MSchirp  The Branch is reverted back to PROD, please have a look and let us know your views on the page.

**Comment by MSchirp** [comment] 2016-04-29 15:10
@dpatil-gmcs 

The layout looks better on the activity page, see link below! (Can you increase the white space between the line and the text 'Activity' & 'Actions', so the text is in precisely in the middle? 

http://hiexistence.com/members/martijn-schirp/activity/ Is still visible when you're not logged in/logged in as a different user. This should be private. 

The @mention tags don't work in normal discussions: http://hiexistence.com/topic/he-5-0-slogan-suggestions/

The @mention doesn't open the list anymore to select a user. It also doesn't recognize it as a mention anymore: see -> http://hiexistence.com/how-to-recognize-an-idiot/

Therefore I can't test if its working.

**Comment by dpatil-gmcs** [comment] 2016-05-02 13:43
@MSchirp  We have made the UI related change, We have made Activity and Actions in the middle. Please have a look.
About the autosuggest list, We will have to research about it, as there seems to be some problem with the plugin we are using for autosuggest.

Please let us know if you have installed any new plugin on the TEST site, Which may cause the problem. We will need to investigate the code for it.

**Comment by dpatil-gmcs** [comment] 2016-05-03 13:39
@MSchirp  Now the autosuggest(suggestion list) is working properly on the TEST site, Please have a look and let us know your views on it.

About the discussions, I think mentions feature is not available for it, We will have to investigate more on it.

**Comment by MSchirp** [comment] 2016-05-04 16:45
@dpatil-gmcs 

http://hiexistence.com/members/martijn-schirp/activity/ Is still not private. I can still see all activity when I am not logged in as the user. 

Regarding the tag and auto-suggest system, the most important reason we want this is for the discussions.

**Comment by dpatil-gmcs** [comment] 2016-05-06 12:45
@MSchirp 

We have made the activity link private and committed the code to the TEST site.

About implementation on the discussions,
If you take a look at the bug trail, it was NEVER mentioned that the @Mentions feature had to be on  Discussions Page until 2 days back. This bug is been in the queue for quite a while now for obvious reasons : Requirements kept on adding / minor enhancements / etc.
Priority was to have @Mentions in Comments, so we worked accrodingly. As per your comment, we can treat this issue as a separate STORY as the same implementation on Discussions Page  entials a lot of implementation and research. 
	
Reverting the code involves much committs and files, so we will have to scan all these files again, which may take more time than implementing @mentions for Discussions.

I would suggest you to go LIVE with these changes, and then we will implement the Discussions related functionality and enhance the functionality.

Please let me know your thoughts on it.

**Comment by MSchirp** [comment] 2016-05-09 09:49
Sounds good, please push live and we will make a new one for discussions and notifications.

**Comment by dpatil-gmcs** [comment] 2016-05-09 13:37
@MSchirp  I have deployed the code to the LIVE site. Please have a look and let me know your views on it.

**Comment by dpatil-gmcs** [comment] 2016-05-12 13:05
@MSchirp  Any updates for us?

**Comment by MSchirp** [comment] 2016-05-17 14:15
Looks good for now!

**Comment by MSchirp** [comment] 2016-05-17 14:20
Actually, the mentions feature doesn't work, and clicking the @username doesn't do anything either.

**Comment by MSchirp** [comment] 2016-05-17 14:20
@dpatil-gmcs

**Comment by dpatil-gmcs** [comment] 2016-05-18 12:38
@MSchirp  We have tested the comment functionality, and we can see the mentions feature and clicking @username works correctly,
Please have a look at the attached screenshots:
1. @mentions feature:
![aftercomment](https://cloud.githubusercontent.com/assets/5171153/15358713/71813456-1d23-11e6-9048-066b6cc0688c.png)

2. Click on @username:
![clickon name](https://cloud.githubusercontent.com/assets/5171153/15358731/894d90f2-1d23-11e6-9f61-206b8fd425d9.png)

**Comment by MSchirp** [comment] 2016-05-18 13:59
Hmm, seems to work now, closing again

**Closed by MSchirp** 2016-05-18 13:59 UTC
Labels: discussing, enhancement, ready for review
