### ISSUE TITLE
HighExistence pages not loading / site seems to have crashed

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#301] opened 2016-06-10 11:00 UTC
I can go on the homepage but when I click on any other page (blog page, discussions), I get this message: 

![screenshot 2016-06-10 12 56 28](https://cloud.githubusercontent.com/assets/13107838/15962397/133b6426-2f0b-11e6-8540-86a37b53737c.png)

I know we're planning on doing a "re-sync" at some point soon, not sure if this is related. This needs to be fixed ASAP.

**Comment by dpatil-gmcs** [comment] 2016-06-10 14:00
@JonBrooksX @MSchirp  We have researched on the issue, and found that, the error occours when the server migratrion from one host to other host is in progress,
It seems that there is some problem with the cPanel, please let me know your views on it.

**Comment by dpatil-gmcs** [comment] 2016-06-20 10:41
@MSchirp  @JonBrooksX   I have tested the different pages of the site for some time. It seems that the site is migrated and the issue is solved,

Hence closing the issue.

**Closed by dpatil-gmcs** 2016-06-20 10:41 UTC
Labels: discussing, urgent
