### ISSUE TITLE
"Sign In" button says "Signin"

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#232] opened 2016-02-03 19:01 UTC
The "Sign In" button should be two words not one.

![screenshot 2016-02-03 18 57 33](https://cloud.githubusercontent.com/assets/13107838/12793386/562d905a-caa8-11e5-942b-1b01fafdec9f.png)

**Comment by dpatil-gmcs** [comment] 2016-02-04 11:21
@JonBrooksX  I have made the changed and deployed the code to the LIVE site with the commit#: d12907ce,
Please have a look and let me know your comments.
As the issue is fixed on LIVE site, Closing the issue!

**Closed by dpatil-gmcs** 2016-02-04 11:21 UTC
Labels: enhancement
